# Generated by Django 3.2.12 on 2025-06-24 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('measurement_model', models.CharField(choices=[('GMM', 'General Measurement Model'), ('PAA', 'Premium Allocation Approach'), ('VFA', 'Variable Fee Approach')], max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked'), ('deleted', 'Deleted')], default='draft', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='model_definitions.modeldefinition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_models', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Definition',
                'verbose_name_plural': 'Model Definitions',
                'ordering': ['-modified_on'],
            },
        ),
        migrations.CreateModel(
            name='ModelDefinitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=50)),
                ('measurement_model', models.CharField(max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='model_definitions.modeldefinition')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Definition History',
                'verbose_name_plural': 'Model Definition History',
                'ordering': ['-saved_at'],
            },
        ),
    ]
