# Generated by Django 3.2.12 on 2025-06-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldefinition',
            name='measurement_model',
        ),
        migrations.RemoveField(
            model_name='modeldefinition',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='modeldefinitionhistory',
            name='measurement_model',
        ),
        migrations.RemoveField(
            model_name='modeldefinitionhistory',
            name='product_type',
        ),
    ]
