# Generated by Django 3.2.12 on 2025-07-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0002_auto_20250627_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldefinition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modeldefinition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modeldefinitionhistory',
            name='description',
        ),
    ]
