# Generated by Django 3.2.12 on 2025-07-06 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_definitions', '0003_auto_20250702_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('expense', 'Expense'), ('claims_paid', 'Claims Paid'), ('outstanding_claims', 'Outstanding Claims'), ('premiums', 'Premiums'), ('commissions_paid', 'Commissions Paid'), ('manual_data', 'Manual Data')], max_length=50)),
                ('template_file', models.FileField(upload_to='data_templates/')),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_standard_template', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Data Upload Template',
                'verbose_name_plural': 'Data Upload Templates',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DataUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('batch_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('batch_status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('validated', 'Validated')], default='draft', max_length=20)),
                ('upload_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload Batch',
                'verbose_name_plural': 'Data Upload Batches',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('upload_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('source', models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging'), ('api', 'API')], max_length=20)),
                ('insurance_type', models.CharField(choices=[('direct_insurance', 'Direct Insurance'), ('reinsurance', 'Reinsurance'), ('group_insurance', 'Group Insurance')], max_length=50)),
                ('data_type', models.CharField(choices=[('expense', 'Expense'), ('claims_paid', 'Claims Paid'), ('outstanding_claims', 'Outstanding Claims'), ('premiums', 'Premiums'), ('commissions_paid', 'Commissions Paid'), ('manual_data', 'Manual Data')], max_length=50)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=5)),
                ('year', models.IntegerField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='data_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('in_progress', 'In Progress'), ('validated', 'Validated'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('rows_processed', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(default=list)),
                ('api_payload', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='model_definitions.datauploadbatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Upload',
                'verbose_name_plural': 'Data Uploads',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='APIUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('reporting_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('sum_of_premiums', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sum_of_paid_claims', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sum_of_commissions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('api_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('data_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_log', to='model_definitions.dataupload')),
            ],
            options={
                'verbose_name': 'API Upload Log',
                'verbose_name_plural': 'API Upload Logs',
                'ordering': ['-upload_date'],
            },
        ),
    ]
