# Generated by Django 3.2.12 on 2025-07-09 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_definitions', '0004_apiuploadlog_dataupload_datauploadbatch_datauploadtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadbatch',
            name='batch_model',
            field=models.CharField(choices=[('PAA', 'PAA'), ('GMM', 'GMM'), ('VFA', 'VFA')], default='GMM', help_text='IFRS 17 model: PAA, GMM, or VFA', max_length=10),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='batch_quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], default='Q1', help_text='Reporting quarter', max_length=10),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='batch_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging')], default='custom', help_text='Upload source type', max_length=20),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='batch_year',
            field=models.IntegerField(default=2025, help_text='Reporting year'),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='insurance_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('reinsurance', 'Reinsurance'), ('group', 'Group')], default='direct', help_text='Insurance type for this batch', max_length=50),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_data_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='name',
            field=models.CharField(blank=True, help_text='Optional batch label', max_length=255),
        ),
        migrations.CreateModel(
            name='DataBatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Foreign key referencing data_batch(batch_id)', max_length=50)),
                ('document_type', models.CharField(choices=[('expense', 'Expense'), ('claims_paid', 'Claims Paid'), ('outstanding_claims', 'Outstanding Claims'), ('premiums', 'Premiums'), ('commissions_paid', 'Commissions Paid'), ('manual_data', 'Manual Data'), ('staging_data', 'Staging Data'), ('reinsurance_data', 'Reinsurance Data'), ('group_data', 'Group Data')], help_text='Type of document (e.g., Expense, Claims Paid, etc.)', max_length=100)),
                ('upload_status', models.BooleanField(default=False, help_text='TRUE if uploaded, FALSE by default')),
            ],
            options={
                'verbose_name': 'Data Batch Status',
                'verbose_name_plural': 'Data Batch Status Records',
                'ordering': ['batch_id', 'document_type'],
                'unique_together': {('batch_id', 'document_type')},
            },
        ),
    ]
