# Generated by Django 3.2.12 on 2025-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0005_auto_20250709_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('batch_type', models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging')], help_text='Custom or Staging', max_length=20)),
                ('batch_model', models.CharField(choices=[('PAA', 'PAA'), ('GMM', 'GMM'), ('VFA', 'VFA')], help_text='PAA, GMM, VFA', max_length=10)),
                ('insurance_type', models.CharField(choices=[('direct', 'Direct'), ('reinsurance', 'Reinsurance'), ('group', 'Group')], help_text='Direct, Reinsurance, Group', max_length=50)),
                ('document_type', models.CharField(help_text='e.g., Premiums, Claims Paid, Manual Data, etc.', max_length=100)),
                ('required', models.BooleanField(default=True, help_text='TRUE if document is required, FALSE if optional')),
                ('template', models.CharField(default='excel file', help_text='Template type (e.g., excel file)', max_length=100)),
            ],
            options={
                'verbose_name': 'Document Type Configuration',
                'verbose_name_plural': 'Document Type Configurations',
                'ordering': ['batch_type', 'batch_model', 'insurance_type', 'document_type'],
                'unique_together': {('batch_type', 'batch_model', 'insurance_type', 'document_type')},
            },
        ),
    ]
