# Generated by Django 3.2.12 on 2025-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0006_documenttypeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypeconfig',
            name='template',
            field=models.FileField(help_text='Excel template file for this document type', upload_to='document_templates/'),
        ),
    ]
