# Generated by Django 3.2.12 on 2025-07-21 16:29

from django.db import migrations, models


def update_batch_status(apps, schema_editor):
    DataUploadBatch = apps.get_model('model_definitions', 'DataUploadBatch')
    
    status_mapping = {
        'draft': 'pending',
        'saved': 'pending', 
        'validated': 'completed'
    }
    
    for batch in DataUploadBatch.objects.all():
        if batch.batch_status in status_mapping:
            batch.batch_status = status_mapping[batch.batch_status]
            batch.save()


def reverse_batch_status(apps, schema_editor):
    DataUploadBatch = apps.get_model('model_definitions', 'DataUploadBatch')
    
    reverse_mapping = {
        'pending': 'draft',
        'completed': 'validated'
    }
    
    for batch in DataUploadBatch.objects.all():
        if batch.batch_status in reverse_mapping:
            batch.batch_status = reverse_mapping[batch.batch_status]
            batch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0007_change_template_to_file_field'),
    ]

    operations = [
        migrations.RunPython(update_batch_status, reverse_batch_status),
        
        migrations.AlterField(
            model_name='datauploadbatch',
            name='batch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
