# Generated by Django 3.2.12 on 2025-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0008_update_batch_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('batch_type', models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging')], help_text='Custom or Staging', max_length=20)),
                ('batch_model', models.CharField(choices=[('PAA', 'PAA'), ('GMM', 'GMM'), ('VFA', 'VFA')], help_text='PAA, GMM, VFA', max_length=10)),
                ('insurance_type', models.CharField(choices=[('direct', 'Direct'), ('reinsurance', 'Reinsurance'), ('group', 'Group')], help_text='Direct, Reinsurance, Group', max_length=50)),
                ('engine_type', models.CharField(help_text='e.g., Data Conversion, Format Transformation, etc.', max_length=100)),
                ('required', models.BooleanField(default=True, help_text='TRUE if engine is required, FALSE if optional')),
                ('script', models.FileField(help_text='Python script file for this conversion engine', upload_to='conversion_scripts/')),
            ],
            options={
                'verbose_name': 'Conversion Engine Configuration',
                'verbose_name_plural': 'Conversion Engine Configurations',
                'ordering': ['batch_type', 'batch_model', 'insurance_type', 'engine_type'],
                'unique_together': {('batch_type', 'batch_model', 'insurance_type', 'engine_type')},
            },
        ),
        migrations.CreateModel(
            name='CalculationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('batch_type', models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging')], help_text='Custom or Staging', max_length=20)),
                ('batch_model', models.CharField(choices=[('PAA', 'PAA'), ('GMM', 'GMM'), ('VFA', 'VFA')], help_text='PAA, GMM, VFA', max_length=10)),
                ('insurance_type', models.CharField(choices=[('direct', 'Direct'), ('reinsurance', 'Reinsurance'), ('group', 'Group')], help_text='Direct, Reinsurance, Group', max_length=50)),
                ('engine_type', models.CharField(help_text='e.g., Premium Calculation, Reserve Calculation, etc.', max_length=100)),
                ('required', models.BooleanField(default=True, help_text='TRUE if engine is required, FALSE if optional')),
                ('script', models.FileField(help_text='Python script file for this calculation engine', upload_to='calculation_scripts/')),
            ],
            options={
                'verbose_name': 'Calculation Engine Configuration',
                'verbose_name_plural': 'Calculation Engine Configurations',
                'ordering': ['batch_type', 'batch_model', 'insurance_type', 'engine_type'],
                'unique_together': {('batch_type', 'batch_model', 'insurance_type', 'engine_type')},
            },
        ),
    ]
