# Generated by Django 3.2.12 on 2025-07-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0009_calculationconfig_conversionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('code', models.CharField(help_text='3-letter currency code (e.g., USD, EUR, GBP)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full currency name (e.g., United States Dollar)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for selection')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('batch_model', models.CharField(choices=[('PAA', 'PAA'), ('GMM', 'GMM'), ('VFA', 'VFA')], help_text='PAA, GMM, VFA', max_length=10)),
                ('insurance_type', models.CharField(choices=[('direct', 'Direct'), ('reinsurance', 'Reinsurance'), ('group', 'Group')], help_text='Direct, Reinsurance, Group', max_length=50)),
                ('line_of_business', models.CharField(help_text='Line of business name (e.g., Term Life Insurance, Auto Insurance)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this line of business is active')),
                ('currency', models.ForeignKey(help_text='Currency for this line of business', on_delete=django.db.models.deletion.CASCADE, related_name='line_of_businesses', to='model_definitions.currency')),
            ],
            options={
                'verbose_name': 'Line of Business',
                'verbose_name_plural': 'Lines of Business',
                'ordering': ['batch_model', 'insurance_type', 'line_of_business'],
                'unique_together': {('batch_model', 'insurance_type', 'line_of_business')},
            },
        ),
    ]
