# Generated by Django 3.2.12 on 2025-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0012_create_ifrs_engine_results_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFRSEngineInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(help_text='Unique Run ID for this engine execution', max_length=50, unique=True)),
                ('model_definition', models.JSONField(help_text='JSON model definition data')),
                ('batch_data', models.JSONField(help_text='JSON batch data from uploads')),
                ('field_parameters', models.JSONField(help_text='JSON field parameters from report generation')),
                ('created_by', models.CharField(help_text='Username or system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Insert timestamp')),
            ],
            options={
                'verbose_name': 'IFRS Engine Input',
                'verbose_name_plural': 'IFRS Engine Inputs',
                'db_table': 'ifrs_engine_inputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ifrsengineresult',
            name='run_id',
            field=models.CharField(default='LEGACY-RUN', help_text='Reference to engine run ID', max_length=50),
        ),
        migrations.AddIndex(
            model_name='ifrsengineresult',
            index=models.Index(fields=['run_id'], name='ifrs_engine_run_id_9c4be4_idx'),
        ),
    ]
