# Generated by Django 3.2.12 on 2025-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0014_remove_lob_from_ifrs_engine_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='report_type',
            field=models.CharField(choices=[('staging_table', 'Staging Table'), ('lrc_movement_report', 'LRC Movement Report'), ('lic_movement_report', 'LIC Movement Report'), ('insurance_revenue_expense_report', 'Insurance Revenue and Expense Report'), ('disclosure_report', 'Disclosure Report (DR)'), ('financial_statement_items_report', 'Financial Statement Items (FSI) Report'), ('coverage_units_report', 'Coverage Units Report'), ('premium_allocation_reconciliation', 'Premium Allocation Reconciliation'), ('loss_component_report', 'Loss Component Report'), ('discount_rate_reconciliation', 'Discount Rate Reconciliation'), ('experience_adjustment_report', 'Experience Adjustment Report'), ('reinsurance_report', 'Reinsurance Report'), ('underlying_assumption_summary', 'Underlying Assumption Summary'), ('reconciliation_to_gaap_report', 'Reconciliation to GAAP Report'), ('csm_rollforward_report', 'CSM Rollforward Report'), ('risk_adjustment_rollforward', 'Risk Adjustment Rollforward'), ('csm_sensitivity_report', 'CSM Sensitivity Report')], help_text='Type of report', max_length=100),
        ),
    ]
