# Generated by Django 3.2.12 on 2026-01-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0016_ifrsapiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.CharField(db_index=True, help_text="Unique identifier for this value (e.g., 'DR.MA.Opening.Liabilities.Total')", max_length=200)),
                ('run_id', models.CharField(db_index=True, help_text='Reference to engine run ID', max_length=50)),
                ('report_type', models.CharField(help_text='Type of report this value belongs to', max_length=50)),
                ('period', models.CharField(help_text="Reporting period (e.g., '2026 Q4')", max_length=20)),
                ('legal_entity', models.CharField(help_text='Legal entity name', max_length=200)),
                ('currency', models.CharField(help_text="Currency code (e.g., 'USD', 'EUR')", max_length=10)),
                ('label', models.CharField(help_text='Human-readable label/description', max_length=300)),
                ('value', models.DecimalField(decimal_places=2, help_text='Calculated numeric value', max_digits=20)),
                ('unit', models.CharField(default='currency', help_text='Unit of measurement (currency, percentage, count, etc.)', max_length=50)),
                ('line_of_business', models.CharField(blank=True, help_text='Line of business', max_length=100, null=True)),
                ('cohort', models.CharField(blank=True, help_text='Cohort identifier', max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, help_text='Group identifier', max_length=100, null=True)),
                ('formula_human_readable', models.TextField(blank=True, help_text='Human-readable formula description', null=True)),
                ('dependencies', models.JSONField(default=list, help_text='List of value_ids this calculation depends on')),
                ('calculation_method', models.CharField(help_text='Calculation method (PAA, GMM, VFA)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional calculation notes from engine', null=True)),
                ('is_missing_data', models.BooleanField(default=False, help_text='Flag if calculation used missing/incomplete data')),
                ('is_override', models.BooleanField(default=False, help_text='Flag if value was manually overridden')),
                ('is_fallback', models.BooleanField(default=False, help_text='Flag if fallback logic was used')),
                ('has_rounding', models.BooleanField(default=False, help_text='Flag if rounding was applied')),
                ('calc_engine_version', models.CharField(help_text='Calculation engine version', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Calculation timestamp')),
                ('engine_result', models.ForeignKey(help_text='Parent IFRS engine result', on_delete=django.db.models.deletion.CASCADE, related_name='calculation_values', to='model_definitions.ifrsengineresult')),
            ],
            options={
                'verbose_name': 'Calculation Value',
                'verbose_name_plural': 'Calculation Values',
                'db_table': 'calculation_values',
                'ordering': ['value_id'],
            },
        ),
        migrations.CreateModel(
            name='InputDataReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(help_text='Name of the input dataset (premiums, claims, etc.)', max_length=200)),
                ('source_snapshot_id', models.CharField(help_text='Snapshot identifier for data version tracking', max_length=200)),
                ('source_hash', models.CharField(blank=True, help_text='Hash of source data for change detection', max_length=64, null=True)),
                ('record_count', models.IntegerField(default=0, help_text='Number of records from this dataset')),
                ('metadata', models.JSONField(default=dict, help_text='Additional dataset-specific metadata')),
                ('calculation_value', models.ForeignKey(help_text='Related calculation value', on_delete=django.db.models.deletion.CASCADE, related_name='input_refs', to='model_definitions.calculationvalue')),
            ],
            options={
                'verbose_name': 'Input Data Reference',
                'verbose_name_plural': 'Input Data References',
                'db_table': 'input_data_references',
                'ordering': ['dataset_name'],
            },
        ),
        migrations.CreateModel(
            name='AssumptionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_type', models.CharField(help_text='Type of assumption (discount_curve, risk_adjustment, etc.)', max_length=100)),
                ('assumption_id', models.CharField(help_text='Unique identifier for this assumption', max_length=200)),
                ('assumption_version', models.CharField(help_text='Version of the assumption', max_length=50)),
                ('effective_date', models.DateField(help_text='Effective date of the assumption')),
                ('metadata', models.JSONField(default=dict, help_text='Additional assumption-specific metadata')),
                ('calculation_value', models.ForeignKey(help_text='Related calculation value', on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='model_definitions.calculationvalue')),
            ],
            options={
                'verbose_name': 'Assumption Reference',
                'verbose_name_plural': 'Assumption References',
                'db_table': 'assumption_references',
                'ordering': ['assumption_type', 'assumption_id'],
            },
        ),
        migrations.AddIndex(
            model_name='calculationvalue',
            index=models.Index(fields=['run_id', 'value_id'], name='calculation_run_id_5ffe59_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationvalue',
            index=models.Index(fields=['run_id', 'report_type'], name='calculation_run_id_d613ce_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationvalue',
            index=models.Index(fields=['value_id'], name='calculation_value_i_4f7a71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calculationvalue',
            unique_together={('run_id', 'value_id')},
        ),
    ]
