# Generated by Django 3.2.12 on 2025-08-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0016_ifrsapiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadbatch',
            name='api_config',
            field=models.ForeignKey(blank=True, help_text='API configuration used for this batch (for API batch type only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_batches', to='model_definitions.ifrsapiconfig'),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='last_run_date',
            field=models.DateTimeField(blank=True, help_text='Last execution date for API batches', null=True),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='next_run_date',
            field=models.DateTimeField(blank=True, help_text='Next scheduled execution date for API batches', null=True),
        ),
        migrations.AddField(
            model_name='datauploadbatch',
            name='schedule',
            field=models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='manual', help_text='Execution schedule for API batches', max_length=20),
        ),
        migrations.AlterField(
            model_name='datauploadbatch',
            name='batch_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('staging', 'Staging'), ('api', 'API')], default='custom', help_text='Upload source type', max_length=20),
        ),
    ]
