# Generated by Django 3.2.12 on 2026-02-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_definitions', '0017_auto_20260125_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('run_id', models.CharField(help_text='Calculation Run ID (e.g., RUN-ABC12345678)', max_length=100)),
                ('report_type', models.CharField(help_text='Type of report (e.g., lrc_movement_report)', max_length=100)),
                ('report_type_display', models.CharField(blank=True, help_text='Display name of the report type', max_length=200)),
                ('model_type', models.CharField(help_text='PAA, GMM, or VFA', max_length=10)),
                ('assign_year', models.IntegerField(help_text='Reporting year this report is submitted for')),
                ('assign_quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='Reporting quarter this report is submitted for', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', help_text='Status of the submitted report', max_length=20)),
                ('ifrs_engine_result_id', models.IntegerField(help_text='Foreign key reference to IFRSEngineResult')),
                ('model_used', models.CharField(blank=True, help_text='Model name and version used', max_length=255)),
                ('batch_used', models.CharField(blank=True, help_text='Batch ID used', max_length=255)),
                ('line_of_business_used', models.TextField(blank=True, help_text='Comma-separated list of LOBs used')),
                ('conversion_engine_used', models.CharField(blank=True, help_text='Conversion engine type used', max_length=255)),
                ('ifrs_engine_used', models.CharField(blank=True, help_text='IFRS engine type used', max_length=255)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submitted Report',
                'verbose_name_plural': 'Submitted Reports',
                'ordering': ['-assign_year', '-assign_quarter', '-created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='submittedreport',
            index=models.Index(fields=['assign_year', 'assign_quarter'], name='model_defin_assign__04bf82_idx'),
        ),
        migrations.AddIndex(
            model_name='submittedreport',
            index=models.Index(fields=['report_type', 'assign_year', 'assign_quarter'], name='model_defin_report__260044_idx'),
        ),
        migrations.AddIndex(
            model_name='submittedreport',
            index=models.Index(fields=['status'], name='model_defin_status_eccc74_idx'),
        ),
    ]
