# Generated by Django 3.2.12 on 2026-02-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_definitions', '0018_add_submitted_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefinition',
            name='definition_type',
            field=models.IntegerField(choices=[(1, 'Direct'), (2, 'Group'), (3, 'Reinsurance')], default=1, help_text='1 = Direct, 2 = Group, 3 = Reinsurance'),
        ),
    ]
