# Generated by Django 3.2.12 on 2023-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
