# Generated by Django 3.2.12 on 2023-10-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_integration', '0002_chat_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id']},
        ),
    ]
