# Generated by Django 3.2.12 on 2023-10-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('gpt_integration', '0004_alter_systemprompt_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', related_query_name='chat', to='sessions.session'),
        ),
    ]
