# Generated by Django 3.2.12 on 2023-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_integration', '0005_chat_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session',
        ),
        migrations.AddField(
            model_name='chat',
            name='session_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
