# Generated by Django 3.2.12 on 2023-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_integration', '0006_auto_20231031_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='session_key',
            new_name='session_user_id',
        ),
    ]
