# Generated by Django 3.2.12 on 2023-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Bot', max_length=255)),
                ('greeting_message', models.CharField(default="Hi, I'm here to help.                 What can I do for you today?", max_length=255)),
                ('bot_style_bg_color', models.CharField(default='#dbc3c3', max_length=255)),
                ('bot_style_text_color', models.CharField(default='#000000', max_length=255)),
                ('human_style_bg_color', models.CharField(default='#2590EB', max_length=255)),
                ('human_style_text_color', models.CharField(default='#ffffff', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
