# Generated by Django 3.2.12 on 2023-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='greeting_message',
            field=models.CharField(default="Hi, I'm here to help. What can I do for you today?", max_length=255),
        ),
    ]
